version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: stock_data_visualizer_image
    container_name: stock_data_visualizer_container
    ports:
      - "5003:5000"
    volumes:
      - .:/app
    environment: 
      -FLASK_DEBUG: 1 
